name: ci

on:
  push:
    branches:
      - main

jobs:

  tests:
    name: Building, testing, and pushing images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      run: |-
        cd pipeline1 && docker build -t singhals912/mgmt590-gcs:${{  github.sha }} .
        docker push singhals912/mgmt590-gcs:${{  github.sha }} && cd ../
        cd pipeline2 && docker build -t singhals912/mgmt590-sql:${{  github.sha }} .
        docker push singhals912/mgmt590-sql:${{  github.sha }}
